-- Chạy với quyền sys/sysdba
CONNECT SYS/123@localhost:1521/QLCSDL as SYSDBA;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.SINHVIEN TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.DONVI TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.NHANVIEN TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.HOCPHAN TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.MOMON TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.DANGKY TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.THONGBAO TO ADMIN WITH GRANT OPTION;



GRANT SELECT ON SCHOOL_USER.DONVI TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.NHANVIEN TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.SINHVIEN TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.HOCPHAN TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.MOMON TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.DANGKY TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.THONGBAO TO ADMIN WITH GRANT OPTION;
