-- Kết nối với SYS
--CONNECT SYS/123@localhost:1521/ORCL AS SYSDBA;

CREATE PLUGGABLE DATABASE QLCSDL
ADMIN USER admin IDENTIFIED BY 123
ROLES = (DBA)
FILE_NAME_CONVERT = ('pdbseed', 'QLCSDL');
SELECT name, open_mode FROM v$pdbs;

-- Mở PDB
ALTER PLUGGABLE DATABASE QLCSDL OPEN;

-- Kiểm tra PDB
-- SELECT name, con_id, open_mode FROM v$pdbs;
-- Chuyển sang PDB
ALTER SESSION SET CONTAINER = QLCSDL;

-- Tạo user
CREATE USER school_user IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE TO school_user;
GRANT UNLIMITED TABLESPACE TO school_user;

-- Kết nối với user
CONNECT school_user/123@localhost:1521/QLCSDL;
-- SHOW CON_NAME;
-- SELECT username, 'OPEN' AS account_status FROM all_users
-- Xóa bảng con trước
-- DROP TABLE ĐANGKY CASCADE CONSTRAINTS;
-- DROP TABLE MOMON CASCADE CONSTRAINTS;
-- DROP TABLE HOCPHAN CASCADE CONSTRAINTS;
-- DROP TABLE SINHVIEN CASCADE CONSTRAINTS;
-- DROP TABLE NHANVIEN CASCADE CONSTRAINTS;
-- Cuối cùng xóa bảng ĐONVI
-- DROP TABLE ĐONVI CASCADE CONSTRAINTS;
-- Tạo bảng ĐONVI trước (chưa có khóa ngoại TRGĐV)
CREATE TABLE ĐONVI (
    MAĐV VARCHAR2(10) PRIMARY KEY,
    TENĐV VARCHAR2(100) NOT NULL,
    LOAIĐV VARCHAR2(10) NOT NULL CHECK (LOAIĐV IN ('Khoa', 'Phòng')),
    TRGĐV VARCHAR2(10)
);

-- Tạo bảng NHANVIEN với khóa ngoại MAĐV tham chiếu đến ĐONVI
CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    PHAI VARCHAR2(4) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    LUONG NUMBER,
    PHUCAP NUMBER,
    DT VARCHAR2(15),
    VAITRO VARCHAR2(20) CHECK (VAITRO IN ('NVCB', 'GV', 'NV PĐT', 'NV PKT', 'NV TCHC', 'NV CTSV', 'TRGĐV')),
    MAĐV VARCHAR2(10) NOT NULL,
    CONSTRAINT fk_nv_dv FOREIGN KEY (MAĐV) REFERENCES ĐONVI(MAĐV)
);

-- Thêm khóa ngoại TRGĐV cho ĐONVI tham chiếu đến NHANVIEN
ALTER TABLE ĐONVI
ADD CONSTRAINT fk_dv_trg FOREIGN KEY (TRGĐV) REFERENCES NHANVIEN(MANV);

-- Tạo bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    PHAI VARCHAR2(4) CHECK (PHAI IN ('Nam', 'Nữ')),
    NGSINH DATE,
    ĐCHI VARCHAR2(200),
    DT VARCHAR2(15),
    KHOA VARCHAR2(10) NOT NULL,
    TINHTRANG VARCHAR2(20) CHECK (TINHTRANG IN ('đang học', 'nghỉ học', 'bảo lưu')),
    CONSTRAINT fk_sv_khoa FOREIGN KEY (KHOA) REFERENCES ĐONVI(MAĐV)
);

-- Tạo bảng HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(100) NOT NULL,
    SOTC NUMBER,
    STLT NUMBER,
    STTH NUMBER,
    MAĐV VARCHAR2(10) NOT NULL,
    CONSTRAINT fk_hp_dv FOREIGN KEY (MAĐV) REFERENCES ĐONVI(MAĐV)
);

-- Tạo bảng MOMON
CREATE TABLE MOMON (
    MAMM VARCHAR2(10) PRIMARY KEY,
    MAHP VARCHAR2(10) NOT NULL,
    MAGV VARCHAR2(10) NOT NULL,
    HK NUMBER(1) CHECK (HK IN (1, 2, 3)),
    NAM NUMBER(4),
    CONSTRAINT fk_mm_hp FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP),
    CONSTRAINT fk_mm_gv FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANV)
);

-- Tạo bảng ĐANGKY
CREATE TABLE ĐANGKY (
    MASV VARCHAR2(10),
    MAMM VARCHAR2(10),
    ĐIEMTH NUMBER(5,2) CHECK (ĐIEMTH BETWEEN 0 AND 10),
    ĐIEMQT NUMBER(5,2) CHECK (ĐIEMQT BETWEEN 0 AND 10),
    ĐIEMCK NUMBER(5,2) CHECK (ĐIEMCK BETWEEN 0 AND 10),
    ĐIEMTK NUMBER(5,2) CHECK (ĐIEMTK BETWEEN 0 AND 10),
    PRIMARY KEY (MASV, MAMM),
    CONSTRAINT fk_dk_sv FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT fk_dk_mm FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM)
);


CONNECT school_user/123@localhost:1521/QLCSDL;
-- Tắt tự động commit để có thể rollback nếu có lỗi
SET AUTOCOMMIT OFF;

-- 1. Chèn dữ liệu vào bảng ĐONVI (Phải thực hiện đầu tiên)
INSERT INTO ĐONVI (MAĐV, TENĐV, LOAIĐV, TRGĐV) VALUES ('HOA', 'Khoa Hóa học', 'Khoa', NULL);
INSERT INTO ĐONVI (MAĐV, TENĐV, LOAIĐV, TRGĐV) VALUES ('PĐT', 'Phòng Đào tạo', 'Phòng', NULL);
COMMIT;

-- 2. Chèn dữ liệu vào bảng NHANVIEN (Thêm trưởng đơn vị trước)
-- Nhân viên là Trưởng khoa Hóa học
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MAĐV) 
VALUES ('NV001', 'Nguyễn Văn A', 'Nam', TO_DATE('1980-01-15', 'YYYY-MM-DD'), 20000000, 5000000, '0912345678', 'TRGĐV', 'HOA');

-- Nhân viên Phòng Đào tạo
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MAĐV) 
VALUES ('NV002', 'Trần Thị B', 'Nữ', TO_DATE('1990-05-20', 'YYYY-MM-DD'), 15000000, 3000000, '0987654321', 'NV PĐT', 'PĐT');

-- Giảng viên Khoa Hóa học
INSERT INTO NHANVIEN (MANV, HOTEN, PHAI, NGSINH, LUONG, PHUCAP, DT, VAITRO, MAĐV) 
VALUES ('GV001', 'Lê Văn C', 'Nam', TO_DATE('1985-10-10', 'YYYY-MM-DD'), 18000000, 4000000, '0905123456', 'GV', 'HOA');
COMMIT;

-- 3. Cập nhật Trưởng đơn vị cho ĐONVI (Sau khi đã có nhân viên)
UPDATE ĐONVI SET TRGĐV = 'NV001' WHERE MAĐV = 'HOA';
UPDATE ĐONVI SET TRGĐV = 'NV002' WHERE MAĐV = 'PĐT';
COMMIT;

-- 4. Chèn dữ liệu vào bảng SINHVIEN
INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, ĐCHI, DT, KHOA, TINHTRANG) 
VALUES ('SV001', 'Phạm Thị D', 'Nữ', TO_DATE('2002-03-25', 'YYYY-MM-DD'), 'Hà Nội', '0911111111', 'HOA', 'đang học');

INSERT INTO SINHVIEN (MASV, HOTEN, PHAI, NGSINH, ĐCHI, DT, KHOA, TINHTRANG) 
VALUES ('SV002', 'Hoàng Văn E', 'Nam', TO_DATE('2003-07-12', 'YYYY-MM-DD'), 'TP.HCM', '0922222222', 'HOA', 'đang học');
COMMIT;

-- 5. Chèn dữ liệu vào bảng HOCPHAN
INSERT INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, MAĐV) 
VALUES ('HP001', 'Hóa đại cương', 3, 30, 15, 'HOA');

INSERT INTO HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, MAĐV) 
VALUES ('HP002', 'Hóa hữu cơ', 4, 45, 20, 'HOA');
COMMIT;

-- 6. Chèn dữ liệu vào bảng MOMON
INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) 
VALUES ('MM20231', 'HP001', 'GV001', 1, 2023);

INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM) 
VALUES ('MM20232', 'HP002', 'GV001', 2, 2023);
COMMIT;

-- 7. Chèn dữ liệu vào bảng ĐANGKY
INSERT INTO ĐANGKY (MASV, MAMM, ĐIEMTH, ĐIEMQT, ĐIEMCK, ĐIEMTK) 
VALUES ('SV001', 'MM20231', 8.5, 7.0, 9.0, (8.5*0.2 + 7.0*0.3 + 9.0*0.5));

INSERT INTO ĐANGKY (MASV, MAMM, ĐIEMTH, ĐIEMQT, ĐIEMCK, ĐIEMTK) 
VALUES ('SV002', 'MM20232', 7.0, 8.5, 8.0, (7.0*0.2 + 8.5*0.3 + 8.0*0.5));
COMMIT;

-- Xác nhận tất cả thay đổi
COMMIT;