-- Kết nối với SYS
CONNECT SYS/123@localhost:1521/xe AS SYSDBA;

-- Đóng PDB nếu đang mở
BEGIN
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE QLCSDL CLOSE IMMEDIATE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-65011, -65257) THEN  -- 65257: cannot close an already closed PDB
            DBMS_OUTPUT.PUT_LINE('Error when closing PDB: ' || SQLERRM);
            RAISE;
        END IF;
END;

-- Xóa PDB nếu tồn tại
BEGIN
    EXECUTE IMMEDIATE 'DROP PLUGGABLE DATABASE QLCSDL INCLUDING DATAFILES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -65011 THEN
            DBMS_OUTPUT.PUT_LINE('Error when dropping PDB: ' || SQLERRM);
            RAISE;
        END IF;
END;
/
