-- Kết nối với SYS
CONNECT SYS/123@localhost:1521/xe AS SYSDBA;

-- Đóng PDB nếu đang mở
BEGIN
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE QLCSDL CLOSE IMMEDIATE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -65011 THEN -- ORA-65011: Pluggable database VPD does not exist.
            RAISE;
        END IF;
END;
/

-- Xóa PDB nếu tồn tại
BEGIN
    EXECUTE IMMEDIATE 'DROP PLUGGABLE DATABASE QLCSDL INCLUDING DATAFILES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -65011 THEN
            RAISE;
        END IF;
END;
/
