-- Chạy với quyền sys/sysdba

GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.SINHVIEN TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.DONVI TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.NHANVIEN TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.HOCPHAN TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.MOMON TO ADMIN WITH GRANT OPTION;
GRANT INSERT, UPDATE, DELETE ON SCHOOL_USER.DANGKY TO ADMIN WITH GRANT OPTION;


GRANT SELECT ON SCHOOL_USER.DONVI TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.NHANVIEN TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.SINHVIEN TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.HOCPHAN TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.MOMON TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.DANGKY TO ADMIN WITH GRANT OPTION;
