-- Chạy với quyền sys/sysdba

GRANT ALL ON SCHOOL_USER.DONVI TO ADMIN;
GRANT ALL ON SCHOOL_USER.SINHVIEN TO ADMIN;
GRANT ALL ON SCHOOL_USER.NHANVIEN TO ADMIN;
GRANT ALL ON SCHOOL_USER.HOCPHAN TO ADMIN;
GRANT ALL ON SCHOOL_USER.MOMON TO ADMIN;
GRANT ALL ON SCHOOL_USER.DANGKY TO ADMIN;

GRANT SELECT ON SCHOOL_USER.DONVI TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.NHANVIEN TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.SINHVIEN TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.HOCPHAN TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.MOMON TO ADMIN WITH GRANT OPTION;
GRANT SELECT ON SCHOOL_USER.DANGKY TO ADMIN WITH GRANT OPTION;

GRANT LBAC_DBA TO admin;
GRANT INHERIT PRIVILEGES ON USER SYS TO admin;
