ALTER SESSION SET CONTAINER = CDB$ROOT;

BEGIN
    LBACSYS.CONFIGURE_OLS; -- This procedure registers Oracle Label Security. 
    LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS; -- This procedure enables it
END;

SHUTDOWN IMMEDIATE; 
STARTUP; 

select * from v$services; 

ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK;
ALTER PLUGGABLE DATABASE QLCSDL CLOSE IMMEDIATE; 
ALTER PLUGGABLE DATABASE QLCSDL OPEN READ WRITE; 
ALTER SESSION SET CONTAINER= QLCSDL; 
SHOW CON_NAME; 

CREATE USER ADMIN_OLS IDENTIFIED BY 123 CONTAINER = CURRENT; 
GRANT CONNECT,RESOURCE TO ADMIN_OLS; --CẤP QUYỀN CONNECT VÀ RESOURCE 
GRANT UNLIMITED TABLESPACE TO ADMIN_OLS; --CẤP QUOTA CHO ADMIN_OLS 
GRANT SELECT ANY DICTIONARY TO ADMIN_OLS; --CẤP QUYỀN ĐỌC DICTIONARY ---> CẤP QUYỀN EXECUTE CHO ADMIN_OLS 
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_user_admin TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_label_admin TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON sa_policy_admin TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON char_to_label TO ADMIN_OLS WITH GRANT OPTION; ---> ADD ADMIN_OLS VÀO LBAC_DBA 
GRANT LBAC_DBA TO ADMIN_OLS; 
GRANT EXECUTE ON sa_sysdba TO ADMIN_OLS;  
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN_OLS; -- CẤP QUYỀN THỰC THI


CONNECT ADMIN_OLS/123@localhost:1521/QLCSDL

BEGIN
  SA_SYSDBA.CREATE_POLICY(
    policy_name     => 'THONGBAO_POLICY',
    column_name     => 'LABEL_COLUMN',
    default_options => 'READ_CONTROL'
  );
END;
/
EXEC SA_SYSDBA.ENABLE_POLICY ('THONGBAO_POLICY'); 

-- 3. Tạo các LEVEL, COMPARTMENT, GROUP (chạy bằng admin)
BEGIN
  -- LEVEL
  SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY', 1, 'SINHVIEN', 'Sinh viên');
  SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY', 2, 'NHANVIEN', 'Nhân viên');
  SA_COMPONENTS.CREATE_LEVEL('THONGBAO_POLICY', 3, 'TRGDV', 'Trưởng đơn vị');

  -- COMPARTMENT
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 10, 'TOAN', 'Khoa Toán');
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 20, 'LY', 'Khoa Lý');
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 30, 'HOA', 'Khoa Hóa');
  SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_POLICY', 40, 'HANHCHINH', 'Hành chính');

  -- GROUP
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 1, 'COSO1', 'Cơ sở 1');
  SA_COMPONENTS.CREATE_GROUP('THONGBAO_POLICY', 2, 'COSO2', 'Cơ sở 2');
END;
/


CONNECT ADMIN_OLS/123@localhost:1521/QLCSDL
-- 4. Tạo label mẫu (chạy bằng admin)
BEGIN
  --SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 101, 'TRGDV', TRUE);
  --SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 102, 'NHANVIEN', TRUE);
  --SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 103, 'SINHVIEN', TRUE);
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 104, 'SVHOACS1', TRUE);
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 105, 'SVHOACS2', TRUE);
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 106, 'SVHOABOTH', TRUE);
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 107, 'TRGDVHANHCHINH', TRUE);
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 108, 'NVHANHCHINHCS1', TRUE);
  SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_POLICY', 109, 'TRGDVHOABOTH', TRUE);
END;
/

DECLARE
  v_label VARCHAR2(100) := 'TRGDV_ALL';
BEGIN
  DBMS_LS.VALIDATE_LABEL(v_label);
  DBMS_OUTPUT.PUT_LINE('Label is valid.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Invalid label: ' || SQLERRM);
END;
/


SELECT argument_name, data_type, in_out, position
FROM all_arguments
WHERE object_name = 'CREATE_LABEL'
  AND package_name = 'SA_LABEL_ADMIN'
ORDER BY position;

-- 5. Gán chính sách OLS vào bảng THONGBAO (chạy bằng admin)
BEGIN
  SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    policy_name     => 'THONGBAO_POLICY',
    schema_name     => 'SCHOOL_USER',
    table_name      => 'THONGBAO',
    column_name     => 'LABEL_COLUMN'
  );
END;
/