-- chạy với quyền SCHOOL_USER

--====== CÂU 1 --======

-- NVCB
CREATE ROLE NVCB;

-- VIEW NHÂN VIÊN XEM THÔNG TIN CỦA MÌNH
CREATE OR REPLACE VIEW NHANVIEN_VIEW AS
SELECT *
FROM NHANVIEN
WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

-- chỉ cho update số điện thoại của bản thân
CREATE OR REPLACE PROCEDURE UPDATE_MY_PHONE (
    NEW_DT IN VARCHAR2
)
IS
BEGIN
    UPDATE NHANVIEN
    SET DT = NEW_DT
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
    
    COMMIT;
END;
/

GRANT SELECT ON NHANVIEN_VIEW TO NVCB;
GRANT EXECUTE ON UPDATE_MY_PHONE TO NVCB;

-- TRGDV
CREATE ROLE TRGDV;

CREATE OR REPLACE VIEW NHANVIEN_TRGDV_VIEW AS
SELECT MANV, HOTEN, PHAI, NGSINH, '***' AS LUONG, '***' AS PHUCAP, DT, VAITRO, MADV
FROM NHANVIEN
WHERE MADV = (SELECT MADV FROM NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));

-- NVTCHC
CREATE ROLE NVTCHC;
GRANT SELECT, INSERT, UPDATE, DELETE ON NHANVIEN TO NVTCHC;


--====== CÂU 2 --======
CREATE ROLE GV;

CREATE OR REPLACE VIEW MOMON_GV_VIEW AS
SELECT * FROM SCHOOL_USER.MOMON
WHERE MAGV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON MOMON_GV_VIEW TO GV;

-- ROLE NVPDT
CREATE ROLE NVPDT;

-- lấy học kì hiện tại
CREATE OR REPLACE FUNCTION GET_HOCKI
RETURN NUMBER
IS
    v_month NUMBER := EXTRACT(MONTH FROM SYSDATE);
BEGIN
    IF v_month BETWEEN 9 AND 12 THEN
        RETURN 1;
    ELSIF v_month BETWEEN 1 AND 4 THEN
        RETURN 2;
    ELSE
        RETURN 3;
    END IF;
END;
/


-- lấy năm bắt đầu của năm học hiện tại
CREATE OR REPLACE FUNCTION GET_NAM
RETURN NUMBER
IS
    v_month NUMBER := EXTRACT(MONTH FROM SYSDATE);
    v_year  NUMBER := EXTRACT(YEAR FROM SYSDATE);
BEGIN
    IF v_month BETWEEN 9 AND 12 THEN
        RETURN v_year;
    ELSE
        RETURN v_year - 1;
    END IF;
END;
/

-- view cho NVPDT xem mở môn
CREATE OR REPLACE VIEW MOMON_NVPDT_VIEW AS
SELECT MAMM, MAHP, MAGV, HK, NAM
FROM SCHOOL_USER.MOMON
WHERE HK = GET_HOCKI() AND NAM = GET_NAM();

CREATE OR REPLACE TRIGGER TRG_MOMON_NVPDT_IO
INSTEAD OF INSERT OR UPDATE OR DELETE ON MOMON_NVPDT_VIEW
FOR EACH ROW
BEGIN
    -- XỬ LÝ INSERT
    IF INSERTING THEN
        IF :NEW.HK != GET_HOCKI() OR :NEW.NAM != GET_NAM() THEN
            RAISE_APPLICATION_ERROR(-20001, 'Chỉ được thêm dữ liệu thuộc học kỳ hiện tại.');
        END IF;

        INSERT INTO MOMON (MAMM, MAHP, MAGV, HK, NAM)
        VALUES (:NEW.MAMM, :NEW.MAHP, :NEW.MAGV, :NEW.HK, :NEW.NAM);

    -- XỬ LÝ UPDATE
    ELSIF UPDATING THEN
        IF :NEW.HK != GET_HOCKI() OR :NEW.NAM != GET_NAM() THEN
            RAISE_APPLICATION_ERROR(-20002, 'Chỉ được cập nhật dữ liệu thuộc học kỳ hiện tại.');
        END IF;

        UPDATE MOMON
        SET MAGV = :NEW.MAGV,
            HK   = :NEW.HK,
            NAM  = :NEW.NAM
        WHERE MAHP = :OLD.MAHP;

    -- XỬ LÝ DELETE
    ELSIF DELETING THEN
        DELETE FROM MOMON
        WHERE MAHP = :OLD.MAHP AND HK = GET_HOCKI() AND NAM = GET_NAM();

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20003, 'Không tìm thấy dữ liệu thuộc học kỳ hiện tại để xóa.');
        END IF;
    END IF;
END;
/;

-- cấp quyền cho NVPDT
GRANT EXECUTE ON GET_HOCKI TO NVPDT;
GRANT EXECUTE ON GET_NAM TO NVPDT;
GRANT SELECT, INSERT, UPDATE ON MOMON_NVPDT_VIEW TO NVPDT;
GRANT DELETE ON MOMON_NVPDT_VIEW TO NVPDT;


-- view xem trưởng phòng được xem các dòng liên quan đến môn do đơn vị của mình làm trưởng
CREATE OR REPLACE VIEW MOMON_TRGDV_VIEW AS
SELECT * FROM SCHOOL_USER.MOMON
WHERE MAGV IN
    (SELECT MANV 
    FROM SCHOOL_USER.NHANVIEN 
    WHERE MADV = 
        (SELECT MADV 
        FROM SCHOOL_USER.NHANVIEN 
        WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER')));


GRANT SELECT ON MOMON_TRGDV_VIEW TO TRGDV;

-- ROLE SV
CREATE ROLE SV;

-- sinh viên được xem các dòng mở môn có liên quan đến mình
CREATE OR REPLACE VIEW MOMON_SINHVIEN_VIEW AS
SELECT * 
FROM SCHOOL_USER.MOMON
WHERE MAHP IN
    (SELECT MAHP FROM HOCPHAN WHERE MADV = 
        (SELECT MADV 
        FROM SINHVIEN
        WHERE MASV = SYS_CONTEXT('USERENV', 'SESSION_USER')));

GRANT SELECT ON MOMON_SINHVIEN_VIEW TO SV;
