-- chạy với quyền SCHOOL_USER

--====== CÂU 1 --======

-- NVCB
CREATE ROLE NVCB;

-- VIEW NHÂN VIÊN XEM THÔNG TIN CỦA MÌNH
CREATE OR REPLACE VIEW NHANVIEN_VIEW AS
SELECT *
FROM NHANVIEN
WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

CREATE OR REPLACE PROCEDURE UPDATE_MY_PHONE (
    NEW_DT IN VARCHAR2
)
IS
BEGIN
    UPDATE NHANVIEN
    SET DT = NEW_DT
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
    
    COMMIT;
END;

COMMIT;

GRANT SELECT ON NHANVIEN_VIEW TO NVCB;
GRANT EXECUTE ON UPDATE_MY_PHONE TO NVCB;

-- TRGDV
CREATE ROLE TRGDV;

CREATE OR REPLACE VIEW NHANVIEN_TRGDV_VIEW AS
SELECT MANV, HOTEN, PHAI, NGSINH, '***' AS LUONG, '***' AS PHUCAP, DT, VAITRO, MADV
FROM NHANVIEN
WHERE MADV = (SELECT MADV FROM NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));

-- NVTCHC
CREATE ROLE NVTCHC;
GRANT SELECT, INSERT, UPDATE, DELETE ON NHANVIEN TO NVTCHC;
