-- chạy với quyền SCHOOL_USER

--====== CÂU 1 --======

-- NVCB
CREATE ROLE NVCB;

-- VIEW NHÂN VIÊN XEM THÔNG TIN CỦA MÌNH
CREATE OR REPLACE VIEW NHANVIEN_VIEW AS
SELECT *
FROM NHANVIEN
WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

CREATE OR REPLACE PROCEDURE UPDATE_MY_PHONE (
    NEW_DT IN VARCHAR2
)
IS
BEGIN
    UPDATE NHANVIEN
    SET DT = NEW_DT
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
    
    COMMIT;
END;

GRANT SELECT ON NHANVIEN_VIEW TO NVCB;
GRANT EXECUTE ON UPDATE_MY_PHONE TO NVCB;

-- TRGDV
CREATE ROLE TRGDV;

CREATE OR REPLACE VIEW NHANVIEN_TRGDV_VIEW AS
SELECT MANV, HOTEN, PHAI, NGSINH, '***' AS LUONG, '***' AS PHUCAP, DT, VAITRO, MADV
FROM NHANVIEN
WHERE MADV = (SELECT MADV FROM NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));

-- NVTCHC
CREATE ROLE NVTCHC;
GRANT SELECT, INSERT, UPDATE, DELETE ON NHANVIEN TO NVTCHC;


--====== CÂU 2 --======
CREATE ROLE GV;

CREATE OR REPLACE VIEW MOMON_GV_VIEW AS
SELECT * FROM MOMON
WHERE MAGV = SYS_CONTEXT('USERENV', 'SESSION_USER');

-- NVPDT
CREATE ROLE NVPDT

CREATE OR REPLACE FUNCTION GET_HOCKI
RETURN NUMBER
IS
    v_month NUMBER := EXTRACT(MONTH FROM SYSDATE);
BEGIN
    IF v_month BETWEEN 9 AND 12 THEN
        RETURN 1;
    ELSIF v_month BETWEEN 1 AND 4 THEN
        RETURN 2;
    ELSE
        RETURN 3;
    END IF;
END;
/

CREATE OR REPLACE FUNCTION GET_NAM
RETURN NUMBER
IS
    v_month NUMBER := EXTRACT(MONTH FROM SYSDATE);
    v_year  NUMBER := EXTRACT(YEAR FROM SYSDATE);
BEGIN
    IF v_month BETWEEN 9 AND 12 THEN
        RETURN v_year;
    ELSE
        RETURN v_year - 1;
    END IF;
END;
/

CREATE OR REPLACE VIEW MOMON_NVPDT_VIEW AS
SELECT *
FROM SCHOOL_USER.MOMON
WHERE HK = GET_HOCKI() AND NAM = GET_NAM();

-- CẤP QUYỀN CHO ROLE    
GRANT EXECUTE ON GET_HOCKI TO NVPDT;
GRANT EXECUTE ON GET_NAM TO NVPDT;
GRANT SELECT ON MOMON_NVPDT_VIEW TO NVPDT;



